import { Flower } from '../types';

export const FLOWERS: Flower[] = [
  {
    id: 'cherry-blossom-1',
    type: 'cherry-blossom',
    name: 'Cherry Blossom',
    color: '#FFB7C5',
    petalCount: 5,
    size: 'small',
    description: 'Delicate pink sakura with 5 petals',
  },
  {
    id: 'chrysanthemum-1',
    type: 'chrysanthemum',
    name: 'White Chrysanthemum',
    color: '#FAFAFA',
    petalCount: 20,
    size: 'large',
    description: 'Layered white chrysanthemum with many petals',
  },
  {
    id: 'iris-1',
    type: 'iris',
    name: 'Purple Iris',
    color: '#6B5B95',
    petalCount: 6,
    size: 'medium',
    description: 'Elegant purple iris with 6 petals',
  },
  {
    id: 'plum-blossom-1',
    type: 'plum-blossom',
    name: 'Red Plum Blossom',
    color: '#E74C3C',
    petalCount: 5,
    size: 'small',
    description: 'Vibrant red plum blossom with rounded petals',
  },
  {
    id: 'forsythia-1',
    type: 'forsythia',
    name: 'Yellow Forsythia',
    color: '#F4D03F',
    petalCount: 4,
    size: 'small',
    description: 'Bright yellow forsythia with 4 petals',
  },
  {
    id: 'lily-1',
    type: 'lily',
    name: 'Orange Lily',
    color: '#FF8C42',
    petalCount: 6,
    size: 'large',
    description: 'Striking orange lily with elongated petals',
  },
  {
    id: 'peony-1',
    type: 'peony',
    name: 'Pink Peony',
    color: '#FADADD',
    petalCount: 15,
    size: 'large',
    description: 'Lush pink peony with ruffled petals',
  },
  {
    id: 'jasmine-1',
    type: 'jasmine',
    name: 'White Jasmine',
    color: '#FFFFFF',
    petalCount: 5,
    size: 'small',
    description: 'Delicate white jasmine with small petals',
  },
  {
    id: 'lotus-1',
    type: 'lotus',
    name: 'Pink Lotus',
    color: '#F4C2C2',
    petalCount: 8,
    size: 'large',
    description: 'Sacred lotus with layered pink petals',
  },
  {
    id: 'camellia-1',
    type: 'camellia',
    name: 'Red Camellia',
    color: '#C41E3A',
    petalCount: 7,
    size: 'medium',
    description: 'Bold red camellia with rounded petals',
  },
  {
    id: 'hydrangea-1',
    type: 'hydrangea',
    name: 'Blue Hydrangea',
    color: '#6495ED',
    petalCount: 4,
    size: 'small',
    description: 'Cluster of small blue hydrangea florets',
  },
  {
    id: 'magnolia-1',
    type: 'magnolia',
    name: 'White Magnolia',
    color: '#FFF5EE',
    petalCount: 6,
    size: 'large',
    description: 'Elegant white magnolia with large petals',
  },
  {
    id: 'wisteria-1',
    type: 'wisteria',
    name: 'Purple Wisteria',
    color: '#9966CC',
    petalCount: 5,
    size: 'small',
    description: 'Cascading purple wisteria blooms',
  },
];
